import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';


interface Region {
  value: string;
  view: string;
}

var dataRegion = [{value: 'EU', view: 'Europa'},{value: 'NA', view: 'Norte Amercia'},{value: 'AF', view: 'Africa'},{value: 'AS', view: 'Asia'},{value:'OC', view: 'Oceania'}, {value:'SA', view: 'Sur America'}];

@Component({
  selector: 'app-scatter-plot',
  templateUrl: './scatter-plot.component.html',
  styleUrls: ['./scatter-plot.component.scss']
})
export class ScatterPlotComponent implements OnInit {

  constructor() { }
  Highcharts = Highcharts;
  chartOptions = {}

  region = "AS";

  regions: Region[] = dataRegion;

  ngOnInit(): void {
    this.chartOptions = {
      chart: {
        type: 'scatter',
        zoomType: 'xy'
      },
      title: {
        text: 'Temperaturas registradas por región'
      },
      xAxis: {
        title: {
          enabled: true,
          text: 'temperatura'
        },
        startOnTick: true,
        endOnTick: true,
        showLastLabel: true
      },
      yAxis: {
        title: {
          text: 'Año'
        }
      },
      legend: {
        layout: 'vertical',
        align: 'left',
        verticalAlign: 'top',
        x: 100,
        y: 70,
        floating: true,
        backgroundColor: Highcharts.defaultOptions.chart.backgroundColor,
        borderWidth: 1
      },
      plotOptions: {
        scatter: {
          marker: {
            radius: 5,
            states: {
              hover: {
                enabled: true,
                lineColor: 'rgb(100,100,100)'
              }
            }
          },
          states: {
            hover: {
              marker: {
                enabled: false
              }
            }
          },
          tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x} cm, {point.y} kg'
          }
        }
      },
      series: []
    };
  }

}


var data = [{
  'EU': [
    {name:"Moldova",
    data:[]},
    {name:"Malta",
    data:[]},
    {name:"Macedonia",
    data:[]},
    {name:"Luxembourg",
    data:[]},
    {name:"Lithuania",
    data:[]},
    {name:"Liechtenstein",
    data:[]},
    {name:"Latvia",
    data:[]},
    {name:"Jersey",
    data:[]},
    {name:"Italy",
    data:[]},
    {name:"Isle Of Man",
    data:[]},
    {name:"Ireland",
    data:[]},
    {name:"Iceland",
    data:[]},
    {name:"Hungary",
    data:[]},
    {name:"Guernsey",
    data:[]},
    {name:"Greece",
    data:[]},
    {name:"Germany",
    data:[]},
    {name:"Finland",
    data:[]},
    {name:"Faroe Islands",
    data:[]},
    {name:"Estonia",
    data:[]},
    {name:"Czech Republic",
    data:[]},
    {name:"Croatia",
    data:[]},
    {name:"Bulgaria",
    data:[]},
    {name:"Bosnia And Herzegovina",
    data:[]},
    {name:"Belgium",
    data:[]},
    {name:"Belarus",
    data:[]},
    {name:"Austria",
    data:[]},
    {name:"Andorra",
    data:[]},
    {name:"Albania",
    data:[]},
    {name:"Aland",
    data:[]},
    {name:"Denmark",
    data:[]},
    {name:"Denmark (Europe)",
    data:[]},
    {name:"France",
    data:[]},
    {name:"France (Europe)",
    data:[]},
    {name:"Netherlands",
    data:[]},
    {name:"Netherlands (Europe)",
    data:[]},
    {name:"United Kingdom",
    data:[]},
    {name:"United Kingdom (Europe)",
    data:[]},
    {name:"Ukraine",
    data:[]},
    {name:"Turkey",
    data:[]},
    {name:"Switzerland",
    data:[]},
    {name:"Sweden",
    data:[]},
    {name:"Svalbard And Jan Mayen",
    data:[]},
    {name:"Spain",
    data:[]},
    {name:"Slovenia",
    data:[]},
    {name:"Slovakia",
    data:[]},
    {name:"Serbia",
    data:[]},
    {name:"San Marino",
    data:[]},
    {name:"Russia",
    data:[]},
    {name:"Romania",
    data:[]},
    {name:"Portugal",
    data:[]},
    {name:"Poland",
    data:[]},
    {name:"Norway",
    data:[]},
    {name:"Montenegro",
    data:[]},
    {name:"Monaco",
    data:[]}
  ],
  'AS': [
    {name:"Afghanistan",
    data:[]},
    {name:"Armenia",
    data:[]},
    {name:"Azerbaijan",
    data:[]},
    {name:"Bahrain",
    data:[]},
    {name:"Bangladesh",
    data:[]},
    {name:"Bhutan",
    data:[]},
    {name:"Cambodia",
    data:[]},
    {name:"China",
    data:[]},
    {name:"Christmas Island",
    data:[]},
    {name:"Cyprus",
    data:[]},
    {name:"Georgia",
    data:[]},
    {name:"Hong Kong",
    data:[]},
    {name:"India",
    data:[]},
    {name:"Indonesia",
    data:[]},
    {name:"Iran",
    data:[]},
    {name:"Iraq",
    data:[]},
    {name:"Israel",
    data:[]},
    {name:"Japan",
    data:[]},
    {name:"Jordan",
    data:[]},
    {name:"Kazakhstan",
    data:[]},
    {name:"Kuwait",
    data:[]},
    {name:"Kyrgyzstan",
    data:[]},
    {name:"Laos",
    data:[]},
    {name:"Lebanon",
    data:[]},
    {name:"Macau",
    data:[]},
    {name:"Malaysia",
    data:[]},
    {name:"Mongolia",
    data:[]},
    {name:"Nepal",
    data:[]},
    {name:"North Korea",
    data:[]},
    {name:"Oman",
    data:[]},
    {name:"Pakistan",
    data:[]},
    {name:"Palestina",
    data:[]},
    {name:"Philippines",
    data:[]},
    {name:"Qatar",
    data:[]},
    {name:"Saudi Arabia",
    data:[]},
    {name:"Singapore",
    data:[]},
    {name:"South Korea",
    data:[]},
    {name:"Sri Lanka",
    data:[]},
    {name:"Syria",
    data:[]},
    {name:"Taiwan",
    data:[]},
    {name:"Tajikistan",
    data:[]},
    {name:"Thailand",
    data:[]},
    {name:"Timor Leste",
    data:[]},
    {name:"Turkmenistan",
    data:[]},
    {name:"United Arab Emirates",
    data:[]},
    {name:"Uzbekistan",
    data:[]},
    {name:"Vietnam",
    data:[]},
    {name:"Yemen",
    data:[]}],
  'NA': [
    {name:"Saint Kitts And Nevis",
data:[]},
{name:"Puerto Rico",
data:[]},
{name:"Panama",
data:[]},
{name:"Nicaragua",
data:[]},
{name:"Montserrat",
data:[]},
{name:"Mexico",
data:[]},
{name:"Martinique",
data:[]},
{name:"Jamaica",
data:[]},
{name:"Honduras",
data:[]},
{name:"Haiti",
data:[]},
{name:"Guatemala",
data:[]},
{name:"Guadeloupe",
data:[]},
{name:"Grenada",
data:[]},
{name:"Greenland",
data:[]},
{name:"El Salvador",
data:[]},
{name:"Dominican Republic",
data:[]},
{name:"Dominica",
data:[]},
{name:"Curarazao",
data:[]},
{name:"Cuba",
data:[]},
{name:"Costa Rica",
data:[]},
{name:"Cayman Islands",
data:[]},
{name:"Canada",
data:[]},
{name:"British Virgin Islands",
data:[]},
{name:"Belize",
data:[]},
{name:"Barbados",
data:[]},
{name:"Bahamas",
data:[]},
{name:"Aruba",
data:[]},
{name:"Antigua And Barbuda",
data:[]},
{name:"Anguilla",
data:[]},
{name:"Virgin Islands",
data:[]},
{name:"United States",
data:[]},
{name:"Turks And Caicas Islands",
data:[]},
{name:"Trinidad And Tobago",
data:[]},
{name:"Sint Maarten",
data:[]},
{name:"Saint Vincent And The Grenadines",
data:[]},
{name:"Saint Pierre And Miquelon",
data:[]},
{name:"Saint Lucia",
data:[]}
  ],
  'SA': [
    {name:"Venezuela",
    data:[]},
    {name:"Uruguay",
    data:[]},
    {name:"Suriname",
    data:[]},
    {name:"Peru",
    data:[]},
    {name:"Paraguay",
    data:[]},
    {name:"Guyana",
    data:[]},
    {name:"French Guiana",
    data:[]},
    {name:"Falkland Islands (Islas Malvinas)",
    data:[]},
    {name:"Ecuador",
    data:[]},
    {name:"Colombia",
    data:[]},
    {name:"Chile",
    data:[]},
    {name:"Brazil",
    data:[]},
    {name:"Bolivia",
    data:[]},
    {name:"Argentina",
    data:[]}
  ],
  'OC': [
    {name:"Tonga",
    data:[]},
    {name:"Solomon Islands",
    data:[]},
    {name:"Samoa",
    data:[]},
    {name:"Papua New Guinea",
    data:[]},
    {name:"Palau",
    data:[]},
    {name:"Northern Mariana Islands",
    data:[]},
    {name:"Niue",
    data:[]},
    {name:"New ZeAland",
    data:[]},
    {name:"New Caledonia",
    data:[]},
    {name:"Kiribati",
    data:[]},
    {name:"Guam",
    data:[]},
    {name:"French Polynesia",
    data:[]},
    {name:"Fiji",
    data:[]},
    {name:"Federated States Of Micronesia",
    data:[]},
    {name:"Australia",
    data:[]},
    {name:"American Samoa",
    data:[]}
 ],
  'AF':[
   {name:"Algeria",
   data: []},
   {name:"Angola",
   data: []},
   {name:"Benin",
   data: []},
   {name:"Botswana",
   data: []},
   {name:"Burundi",
   data: []},
   {name:"Cameroon",
   data: []},
   {name:"Cape Verde",
   data: []},
   {name:"Central African Republic",
   data: []},
   {name:"Chad",
   data: []},
   {name:"Comoros",
   data: []},
   {name:"Democratic Republic Of The Congo",
   data: []},
   {name:"Congo",
   data: []},
   {name:"Djibouti",
   data: []},
   {name:"Egypt",
   data: []},
   {name:"Equatorial Guinea",
   data: []},
   {name:"Eritrea",
   data: []},
   {name:"Ethiopia",
   data: []},
   {name:"Gabon",
   data: []},
   {name:"Gambia",
   data: []},
   {name:"Ghana",
   data: []},
   {name:"Guinea Bissau",
   data: []},
   {name:"Guinea",
   data: []},
   {name:"Kenya",
   data: []},
   {name:"Lesotho",
   data: []},
   {name:"Liberia",
   data: []},
   {name:"Libya",
   data: []},
   {name:"Madagascar",
   data: []},
   {name:"Malawi",
   data: []},
   {name:"Mali",
   data: []},
   {name:"Mauritania",
   data: []},
   {name:"Mauritius",
   data: []},
   {name:"Mayotte",
   data: []},
   {name:"Morocco",
   data: []},
   {name:"Mozambique",
   data: []},
   {name:"Namibia",
   data: []},
   {name:"Niger",
   data: []},
   {name:"Nigeria",
   data: []},
   {name:"Rwanda",
   data: []},
   {name:"Sao Tome And Principe",
   data: []},
   {name:"Senegal",
   data: []},
   {name:"Seychelles",
   data: []},
   {name:"Somalia",
   data: []},
   {name:"South Africa",
   data: []},
   {name:"Sudan",
   data: []},
   {name:"Swaziland",
   data: []},
   {name:"Tanzania",
   data: []},
   {name:"Togo",
   data: []},
   {name:"Tunisia",
   data: []},
   {name:"Uganda",
   data: []},
   {name:"Western Sahara",
   data: []},
   {name:"Zambia",
   data: []},
   {name:"Zimbabwe",
   data: []}
 ],
}]